### ISSUE TITLE
Define parameters and terminology in appropriate sections

### ISSUE THREAD

**Issue by dwaite** [ietf-wg-jose/json-web-proof#77]
From @OR13, https://mailarchive.ietf.org/arch/msg/jose/GkL3I9hEoKjaIDCgno_rYqQsSP0/ :

> Assume the reader has some awareness of JOSE, and introduce terms like `issuer_header` and `presentation_header` so that they defined in their sections, for example:
>
> https://datatracker.ietf.org/doc/html/draft-ietf-jose-json-proof-algorithms-00#name-presentation-protected-header-2
>
> does not include "presentation_header" header.

**Comment by selfissued** [comment]
Typographically, we should use names like "Issuer Header" rather than `issuer_header` for things that are not parameter or field names.

**Comment by dwaite** [comment]
While this particular example seems solved, we have two general issues:

1. algorithmic values and JSON parameters may have the same choice in snake vs camel vs upper case - we may wish to have two styles here for clarity
2. we have definitions and processing steps in single use algorithm that should be raised to be generalized.
