### ISSUE TITLE
what about JWE?

### ISSUE THREAD

**Issue by brentzundel** [ietf-wg-jose/json-web-proof#83]
What, if any, should the relationship be between JWP and JWE?

This Issue is to track the question that was brought up during IETF 117.

**Comment by selfissued** [comment]
My initial gut reaction to this is that ZKPs are more like signatures than encryption.  I *think* that encryption is out of scope.

That said, we may want to describe encrypting a JWP object with JWE.

**Comment by dwaite** [comment]
I suspect that encryption with JWP are going to be part of storage protection or transport, e.g. wrapping a JWP in JWE.

**Comment by dwaite** [comment]
Setting a reminder for draft 6 to potentially describe JWE wrapping a JWP for issuance/presentation.
